from crewai import Task, Agent
from textwrap import dedent
from Quiz.models import Info, MCQQuestions, ShortQuestions, List


class QuizTasks:

    def mcq_questions(
        self, agent: Agent, topic: str, count: int, context: List[Task]
    ) -> Task:
        return Task(
            context=context,
            description=dedent(
                f"""Use the information provided in context about {topic} and generate {count} unique multiple choice questions on the provided topic. 
            Make sure all questions are unique and also increase the difficulty level gradually of every next question you generate. 
            All mcq questions should have four different choices as answer. 
            You also need to assign marks in the range [1,2,3] based on the level of difficulty.
            Make sure all the questions have 1 correct choice and 3 incorrect choices."""
            ),
            expected_output="""You should return a json object of question dictionary in the following format:
                                   {
                                   multiple_choice_questions: [ 
                                   question_statement: str,
                                   associated_marks: int,
                                   difficulty_level: str,
                                   answers: {
                                            correct: str, 
                                            incorrect: List[str]
                                        }
                                   ]}""",
            output_pydantic=MCQQuestions,
            agent=agent,
        )

    def short_questions(
        self, agent: Agent, topic: str, count: int, context: List[Task]
    ) -> Task:
        return Task(
            context=context,
            description=dedent(
                f"""Use the information provided in context about {topic} and generate {count} unique short answer questions. 
            Make sure all questions are unique and also increase the difficulty level gradually of every next question you generate.
            Please provide one-liner answers to the questions generated by you as well.
            You also need to assign marks in the range [2,3,4] based on the level of difficulty.
            Make sure all the questions and answers are precise and in correct format."""
            ),
            expected_output="""You should return a json object of question dictionary in the following format:
                                   {
                                    short_answer_questions : [ 
                                        question_statement: str,
                                        associated_marks: int,
                                        difficulty_level: str,
                                        answer: str,
                                        ]
                                   }""",
            output_pydantic=ShortQuestions,
            agent=agent,
        )

    def gather_knowledge(self, agent: Agent, topic: str) -> Task:
        return Task(
            description=dedent(
                f"""Gather all the knowledge available on {topic} and arange it in precise and concise points. 
                Make sure the points provide every bit of information available about {topic}."""
            ),
            expected_output="""You should return a json object in the following format:
                                   {
                                    topic: str,
                                    points: [
                                        {
                                        heading: str,
                                        content: List[str]
                                        }
                                    ]
                                   }""",
            output_pydantic=Info,
            agent=agent,
        )
